<div class="topo-table">
    <a class="btn btn-success" href="<?php echo $this->url('solicitacao', array('action' => 'novo'))?>">Nova Solicitação</a>
 
    <div class="btn-group">
        <button class="btn">005</button>
        <button data-toggle="dropdown" class="btn dropdown-toggle"><span class="caret"></span></button>
        <ul class="dropdown-menu pull-right" style="min-width: 74px">
            <li class="active"><a href="#">005</a></li>
            <li><a href="#">010</a></li>
            <li><a href="#">025</a></li>
            <li><a href="#">050</a></li>
            <li><a href="#">100</a></li>
        </ul>
    </div>
 
    <div class="input-append pull-right">
        <form>
            <input class="span2" placeholder="Localizar" id="appendedInputButtons" type="text">
            <button class="btn" type="button">Unid. Solicitante</button>
            <button class="btn" type="button">Nome</button>
        </form>
    </div>
</div>
 
<br />
 
<div class="corpo-table">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Solicitante</th>
                <th>Destino</th>
                <th>Objetivo</th>
                <th>Data</th>  
                <th>Ação</th>  
            </tr>
        </thead>
        <tbody>
            <?php for ($i = 1; $i <= 5; $i++): ?>
                <tr>
                    <td><?php echo $i; ?></td>
                    <td>CMTI</td>
                    <td>Promotoria da Capital</td>
                    <td>Apresentar sistema</td>
                    <td>29/01/2013</td>
                    <td>
                        <a class="btn btn-mini btn-info" href="<?php echo $this->url('solicitacao', array("action" => "detalhe", "id" => $i,)); ?>">Visualizar</a>
                        <a class="btn btn-mini btn-warning" href="<?php echo $this->url('solicitacao', array("action" => "editar", "id" => $i,)); ?>">Editar</a>
                        <a class="btn btn-mini btn-danger" href="<?php echo $this->url('solicitacao', array("action" => "deletar", "id" => $i,)); ?>">Apagar</a>
                    </td>
                </tr>
            <?php endfor; ?>
        </tbody>
    </table>
 
    <div class="pagination">
        <ul>
            <li><a href="#">Anterior</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">Próximo</a></li>
        </ul>
    </div>
</div>
